import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

function readMcpSource(projectRoot) {
  const mcpPath = join(projectRoot, ".mcp.json");
  if (!existsSync(mcpPath)) {
    throw new Error(".mcp.json is missing; cannot generate host configurations");
  }
  const raw = readFileSync(mcpPath, "utf8");
  return JSON.parse(raw);
}

function httpHeaderEnv(name, headers) {
  if (headers === undefined) return null;
  const entries = headers === null || typeof headers !== "object" ? [] : Object.entries(headers);
  const value = entries[0]?.[1];
  const match = typeof value === "string" ? value.match(/^\$\{([A-Z][A-Z0-9_]*)\}$/) : null;
  if (entries.length !== 1 || !match) {
    throw new Error(
      `.mcp.json HTTP server ${name} headers must be exactly one "\${ENV_VAR}" placeholder — a literal value would commit a credential`,
    );
  }
  return match[1];
}

/**
 * Generates project-scoped Claude Code MCP configuration.
 */
export function generateClaudeMcpConfig(projectRoot, options = {}) {
  const source = options.source ?? readMcpSource(projectRoot);
  const servers = source.mcpServers ?? {};
  return {
    mcpServers: servers,
  };
}

/**
 * Generates project-scoped Codex TOML configuration (.codex/config.toml).
 */
export function generateCodexConfig(projectRoot, options = {}) {
  const source = options.source ?? readMcpSource(projectRoot);
  const servers = source.mcpServers ?? {};
  const maxThreads = options.maxConcurrentThreads ?? 4;

  const sections = [
    "# Generated by scripts/sync-agent-config.mjs from .mcp.json and .agents/agents/.",
    "# Trust this project before Codex loads project-scoped MCP servers.",
    "[agents]",
    `max_concurrent_threads_per_session = ${maxThreads}`,
  ];

  for (const [name, server] of Object.entries(servers)) {
    if (!/^[A-Za-z0-9_-]+$/.test(name)) {
      throw new Error(`.mcp.json server name is not TOML-safe: ${name}`);
    }
    sections.push("", `# Source server: ${name}`, `[mcp_servers.workspace-${name}]`);
    if (typeof server.command === "string") {
      if (!Array.isArray(server.args) || server.args.some((arg) => typeof arg !== "string")) {
        throw new Error(`.mcp.json stdio server ${name} must have a string args array`);
      }
      sections.push(`command = ${JSON.stringify(server.command)}`);
      sections.push(`args = [${server.args.map((arg) => JSON.stringify(arg)).join(", ")}]`);
    } else if (server.type === "http" && typeof server.url === "string") {
      const headerEnv = httpHeaderEnv(name, server.headers);
      sections.push(`url = ${JSON.stringify(server.url)}`);
      if (headerEnv) sections.push(`bearer_token_env_var = ${JSON.stringify(headerEnv)}`);
    } else {
      throw new Error(`.mcp.json server ${name} must be stdio command/args or HTTP type/url`);
    }
  }

  return `${sections.join("\n")}\n`;
}

/**
 * Generates project-scoped Codex Plugin MCP configuration (.codex-plugin/mcp.json).
 */
export function generateCodexPluginMcp(projectRoot, options = {}) {
  const source = options.source ?? readMcpSource(projectRoot);
  const servers = source.mcpServers ?? {};
  const directMap = {};

  for (const [name, server] of Object.entries(servers)) {
    if (typeof server.command === "string" && Array.isArray(server.args)) {
      directMap[name] = { command: server.command, args: server.args };
    } else if (server.type === "http" && typeof server.url === "string") {
      directMap[name] =
        server.headers === undefined
          ? { url: server.url }
          : { url: server.url, headers: server.headers };
    }
  }

  return `${JSON.stringify(directMap, null, 2)}\n`;
}

/**
 * Generates project-scoped Cursor MCP configuration (.cursor/mcp.json).
 */
export function generateCursorMcp(projectRoot, options = {}) {
  const source = options.source ?? readMcpSource(projectRoot);
  return `${JSON.stringify(source, null, 2)}\n`;
}

/**
 * Generates project-scoped Hermes profile configuration (.hermes/profile/config.yaml).
 */
export function generateHermesConfig(options = {}) {
  const maxChildren = options.maxConcurrentChildren ?? 4;
  const maxDepth = options.maxSpawnDepth ?? 2;
  return `# Generated profile configuration. No credentials belong in this file.\nterminal:\n  backend: local\n  cwd: "\${PROJECT_ROOT}"\nskills:\n  external_dirs:\n    - "\${PROJECT_ROOT}/.agents/skills"\ndelegation:\n  max_concurrent_children: ${maxChildren}\n  max_spawn_depth: ${maxDepth}\n  orchestrator_enabled: true\n`;
}

/**
 * Generates project-scoped OpenClaw configuration template (.openclaw/config.json5).
 */
export function generateOpenclawConfig() {
  return `// Generated by scripts/sync-agent-config.mjs. Non-secret template — no credentials
// belong in this file, and nothing in this repository edits your global OpenClaw
// configuration. Merge into ~/.openclaw/openclaw.json yourself and replace
// <PROJECT_ROOT> with this repository's absolute path.
//
// With the repository as the agent workspace, OpenClaw reads AGENTS.md at the root
// and discovers .agents/skills natively. skills.load.extraDirs covers an agent that
// keeps a different workspace.
{
  agents: {
    list: [
      { id: "agentic-ship", workspace: "<PROJECT_ROOT>" },
    ],
  },
  skills: {
    load: {
      extraDirs: ["<PROJECT_ROOT>/.agents/skills"],
    },
  },
}
`;
}

/**
 * Generates a bundle of all project-scoped host configurations for supported AI hosts.
 */
export function generateAllHostMcpConfigs(projectRoot, options = {}) {
  const source = options.source ?? readMcpSource(projectRoot);
  return {
    claude: {
      path: ".claude/mcp.json",
      content: JSON.stringify(generateClaudeMcpConfig(projectRoot, { source }), null, 2) + "\n",
    },
    codex: {
      path: ".codex/config.toml",
      content: generateCodexConfig(projectRoot, { source }),
    },
    codexPlugin: {
      path: ".codex-plugin/mcp.json",
      content: generateCodexPluginMcp(projectRoot, { source }),
    },
    cursor: {
      path: ".cursor/mcp.json",
      content: generateCursorMcp(projectRoot, { source }),
    },
    hermes: {
      path: ".hermes/profile/config.yaml",
      content: generateHermesConfig(),
    },
    openclaw: {
      path: ".openclaw/config.json5",
      content: generateOpenclawConfig(),
    },
  };
}
